import Image from "next/image"; import { Reveal } from "@/components/Reveal"; import Link from "next/link";
export const metadata={title:"About Nexora Interiors | Tirunelveli",description:"Discover the design philosophy behind Nexora Interiors in Tirunelveli."};
export default function About(){return <main className="pt-[76px]">
 <section className="container-nx py-24 md:py-36"><p className="text-xs font-bold uppercase tracking-[.25em] text-olive">About Nexora</p><h1 className="display mt-6 max-w-5xl font-display text-6xl md:text-9xl">We design for<br/><i>real life.</i></h1><p className="mt-10 max-w-2xl text-lg leading-8 text-black/60">Nexora Interiors is an interior design studio based in Tirunelveli, creating considered residential and commercial spaces with a strong focus on function, materiality and lasting beauty.</p></section>
 <section className="relative h-[520px]"><Image src="https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=2000&q=85" alt="Nexora Interiors style detail" fill className="object-cover"/></section>
 <section className="container-nx grid gap-14 py-24 md:grid-cols-3"><Reveal><p className="text-xs font-bold uppercase tracking-[.2em] text-olive">Our philosophy</p></Reveal><Reveal delay={.1} className="md:col-span-2"><h2 className="font-display text-5xl md:text-7xl">Less noise. More <i>character.</i></h2><p className="mt-7 max-w-2xl text-lg leading-8 text-black/60">We believe the best interiors do not need to shout. Proportion, light, storage, textures and a few well-chosen pieces can make a room feel deeply personal.</p></Reveal></section>
 <section className="bg-sand py-24"><div className="container-nx grid gap-10 md:grid-cols-3">{[["01","Listen","We start by understanding how you live, work and move through the space."],["02","Shape","We turn requirements into a clear design language, with practical decisions at every stage."],["03","Deliver","We coordinate details through execution so the finished space reflects the approved design."]].map((x,i)=><Reveal key={x[0]} delay={i*.08}><div className="border-t border-black/15 pt-6"><span className="font-display text-2xl">{x[0]}</span><h3 className="mt-10 font-display text-4xl">{x[1]}</h3><p className="mt-4 leading-7 text-black/60">{x[2]}</p></div></Reveal>)}</div></section>
 <section className="container-nx py-24 text-center"><h2 className="font-display text-5xl md:text-7xl">Have a space in mind?</h2><Link href="/consultation" className="mt-8 inline-block rounded-full bg-ink px-7 py-4 text-xs font-bold uppercase tracking-widest text-white">Talk to Nexora →</Link></section>
 </main>}
