export const projects=[
 {slug:"earth-and-ivory",title:"Earth & Ivory Residence",category:"Residential",location:"Tirunelveli",style:"Warm contemporary",area:"2,100 sq.ft.",image:"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=85",description:"A calm, tactile home built around warm neutrals, natural textures and practical family living."},
 {slug:"quiet-luxury-kitchen",title:"Quiet Luxury Kitchen",category:"Kitchen",location:"Palayamkottai",style:"Modern classic",area:"240 sq.ft.",image:"https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=1400&q=85",description:"A refined kitchen where generous storage, warm timber and stone surfaces create an effortless daily rhythm."},
 {slug:"studio-24",title:"Studio 24",category:"Commercial",location:"Tirunelveli",style:"Contemporary",area:"3,400 sq.ft.",image:"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=85",description:"A flexible workspace designed to feel focused, welcoming and distinctly brand-led."},
 {slug:"sunlit-living",title:"Sunlit Living",category:"Apartment",location:"Tirunelveli",style:"Soft minimal",area:"1,450 sq.ft.",image:"https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1400&q=85",description:"Soft daylight, layered textures and clean-lined furniture shape an apartment with a quiet personality."},
 {slug:"olive-bedroom",title:"Olive Bedroom",category:"Bedroom",location:"Tirunelveli",style:"Organic modern",area:"220 sq.ft.",image:"https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1400&q=85",description:"An intimate retreat pairing muted greens, timber detailing and carefully controlled lighting."},
 {slug:"crafted-villa",title:"Crafted Villa",category:"Villa",location:"Nanguneri",style:"Modern tropical",area:"3,800 sq.ft.",image:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85",description:"A spacious villa interior that balances strong architectural lines with handcrafted warmth."}
];
export const services=[
 {slug:"residential-interiors",title:"Residential Interiors",desc:"Complete interiors for apartments, independent homes and villas—planned around how you actually live.",image:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=85"},
 {slug:"commercial-interiors",title:"Commercial Interiors",desc:"Workspaces, retail environments and hospitality spaces that translate your brand into a physical experience.",image:"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=85"},
 {slug:"modular-kitchens",title:"Modular Kitchens",desc:"Elegant, efficient kitchens with intelligent storage, durable finishes and hardware selected for daily use.",image:"https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1400&q=85"},
 {slug:"custom-furniture",title:"Custom Furniture",desc:"Made-to-measure pieces that solve awkward spaces and add a distinctive layer to your interiors.",image:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1400&q=85"}
];
